name: Build Docker

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build . -f php/8.0/alpine/Dockerfile -t limingxinleo/docker-workspace:php-8.0
      - name: Publish
        run: |
          docker login -u limingxinleo -p ${{ secrets.DOCKER_TOKEN }}
          docker push limingxinleo/docker-workspace:php-8.0
          
